version: "3.3"
services:

  pytorch-develop:
    container_name: 'torch-develop'
    build: .
    runtime: nvidia
    tty: true
    volumes:
      - ./:/home/
    profiles:
      - develop

  mlflow-training:
    container_name: 'torch-mlflow'
    build: .
    runtime: nvidia
    tty: true
    command: "python3 mlflow-pipeline.py"
    volumes:
      - ./:/home/
    profiles:
      - mlflow

  pytorch-training:
    container_name: 'torch'
    build: .
    runtime: nvidia
    tty: true
    command: "python3 pipeline.py"
    volumes:
      - ./:/home/
    profiles:
      - torch