version: "3.3"
services:
  mlflow-server:
    container_name: 'mlflow'
    build: .
    tty: true
    restart: unless-stopped
    ports:
      - "8686:8686"
    volumes:
      - ../:/home/
      
    command: bash -c "cd /home/ & mlflow server -p 8686 --host 0.0.0.0"
